### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by tony** [tlocke/flake8-alphabetize#6]
Thank you for the project!

I come here from https://github.com/PyCQA/flake8-import-order/issues/163 where license was being brought up

Is there any reason why UNLICENSE was picked instead of ISC / MIT / BSD / [whatever flake8 uses](https://github.com/PyCQA/flake8/blob/main/LICENSE)?

The reason I bring it up is I've heard some about the ambiguity of UNLICENSE

**Comment by tlocke** [comment]
Hi @tony, I'm open to changing the license. I like the MIT license, except for the attribution clause. So how about the MIT-0 license? https://choosealicense.com/licenses/mit-0/

**Comment by tony** [comment]
@tlocke 

I assume the attribution is this: "The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."

If so MIT-0 makes sense. Similar enough to flake8's

**Comment by tlocke** [comment]
Yes that's right. I've made that change now.

**Comment by tony** [comment]
@tlocke Huzzah! Perhaps worth mentioning in https://github.com/PyCQA/flake8-import-order/issues/163?
